name: HnVue Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-release:
    name: Build Release Artifacts
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.x'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: version
        run: |
          $Tag = "${{ github.ref_name }}"
          $Version = $Tag -replace '^v', ''
          echo "version=$Version" >> $env:GITHUB_OUTPUT
          echo "Building version: $Version"

      - name: Build C++ release
        run: |
          cmake --preset release
          cmake --build --preset release --target all-libs --config Release

      - name: Build C# release
        run: |
          dotnet restore HnVue.sln
          dotnet publish HnVue.Console/HnVue.Console.csproj -c Release `
            --self-contained false `
            -o artifacts/publish/HnVue.Console-${{ steps.version.outputs.version }}

      - name: Run tests
        run: |
          ctest --preset release
          dotnet test HnVue.sln -c Release --no-build

      - name: Create release archive
        run: |
          $Version = "${{ steps.version.outputs.version }}"
          $ArchiveName = "HnVue-$Version-windows.zip"

          # Create archive
          Compress-Archive -Path `
            artifacts/publish/HnVue.Console-$Version/**, `
            build/libs/**/*.dll, `
            LICENSE, `
            README.md `
            -DestinationPath "artifacts/$ArchiveName"

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: artifacts/*.zip
          retention-days: 90

      - name: Create GitHub Release (if applicable)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          # TODO: Implement GitHub release creation via gh CLI
          # This requires GitHub token configuration
          Write-Host "Release tag: ${{ github.ref_name }}"
          Write-Host "Version: ${{ steps.version.outputs.version }}"
