#!/usr/bin/env bash
# generate-proto.sh - Generate C++ gRPC stubs from proto files
# SPEC-IPC-001: Proto compilation for IPC layer

set -euo pipefail

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Directories
PROTO_DIR="${PROJECT_ROOT}/proto"
CPP_OUTPUT_DIR="${PROJECT_ROOT}/libs/hnvue-ipc/generated"

# Proto files to compile (exclude hnvue_ipc.proto - it's just an import stub)
PROTO_FILES=(
    "hnvue_common.proto"
    "hnvue_command.proto"
    "hnvue_image.proto"
    "hnvue_health.proto"
    "hnvue_config.proto"
)

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check protoc
    if ! command -v protoc &> /dev/null; then
        log_error "protoc not found. Please install Protocol Buffers compiler:"
        log_error "  Ubuntu/Debian: sudo apt-get install protobuf-compiler"
        log_error "  macOS: brew install protobuf"
        log_error "  Windows: vcpkg install protobuf"
        exit 1
    fi

    # Check grpc_cpp_plugin
    if ! command -v grpc_cpp_plugin &> /dev/null; then
        log_error "grpc_cpp_plugin not found. Please install gRPC:"
        log_error "  Ubuntu/Debian: sudo apt-get install grpc-plugins"
        log_error "  macOS: brew install grpc"
        log_error "  Windows: vcpkg install grpc"
        exit 1
    fi

    local protoc_version=$(protoc --version | awk '{print $2}')
    local grpc_version=$(grpc_cpp_plugin --version 2>&1 | grep -oP 'libgrpc.*' || echo "unknown")

    log_info "protoc version: ${protoc_version}"
    log_info "gRPC plugin: ${grpc_version}"

    # Check proto directory
    if [[ ! -d "${PROTO_DIR}" ]]; then
        log_error "Proto directory not found: ${PROTO_DIR}"
        exit 1
    fi

    # Check proto files exist
    for proto_file in "${PROTO_FILES[@]}"; do
        local proto_path="${PROTO_DIR}/${proto_file}"
        if [[ ! -f "${proto_path}" ]]; then
            log_error "Proto file not found: ${proto_path}"
            exit 1
        fi
    done

    log_info "All prerequisites satisfied."
}

# Create output directory
create_output_dir() {
    log_info "Creating output directory: ${CPP_OUTPUT_DIR}"
    mkdir -p "${CPP_OUTPUT_DIR}"
}

# Generate C++ stubs
generate_cpp_stubs() {
    log_info "Generating C++ gRPC stubs..."

    local protoc_args=(
        --proto_path="${PROTO_DIR}"
        --cpp_out="${CPP_OUTPUT_DIR}"
        --grpc_out="${CPP_OUTPUT_DIR}"
        --plugin=protoc-gen-grpc="$(command -v grpc_cpp_plugin)"
    )

    # Add proto files
    for proto_file in "${PROTO_FILES[@]}"; do
        protoc_args+=("${PROTO_DIR}/${proto_file}")
    done

    # Generate
    protoc "${protoc_args[@]}"

    log_info "C++ stubs generated successfully."
}

# Verify generated files
verify_generated_files() {
    log_info "Verifying generated files..."

    local expected_files=0
    local found_files=0

    for proto_file in "${PROTO_FILES[@]}"; do
        local base_name=$(basename "${proto_file}" .proto)

        # Check for generated files
        local files=(
            "${CPP_OUTPUT_DIR}/${base_name}.pb.h"
            "${CPP_OUTPUT_DIR}/${base_name}.pb.cc"
            "${CPP_OUTPUT_DIR}/${base_name}.grpc.pb.h"
            "${CPP_OUTPUT_DIR}/${base_name}.grpc.pb.cc"
        )

        for file in "${files[@]}"; do
            ((expected_files++))
            if [[ -f "${file}" ]]; then
                ((found_files++))
                log_info "  ✓ $(basename "${file}")"
            else
                log_warn "  ✗ Missing: $(basename "${file}")"
            fi
        done
    done

    if [[ ${found_files} -eq ${expected_files} ]]; then
        log_info "All ${expected_files} expected files generated successfully."
        return 0
    else
        log_error "Generated ${found_files}/${expected_files} expected files."
        return 1
    fi
}

# Print summary
print_summary() {
    log_info "=========================================="
    log_info "Proto generation completed successfully!"
    log_info "=========================================="
    echo ""
    log_info "Generated files location: ${CPP_OUTPUT_DIR}"
    echo ""
    log_info "Next steps:"
    log_info "  1. Build the C++ project: cmake --build build"
    log_info "  2. Run tests: ctest --test-dir build"
    log_info "  3. C# files are auto-generated by MSBuild"
    echo ""
}

# Main execution
main() {
    log_info "HnVue Proto File Generator"
    log_info "============================"
    echo ""

    check_prerequisites
    create_output_dir
    generate_cpp_stubs
    verify_generated_files
    print_summary
}

# Run main
main "$@"
